### ISSUE TITLE
UI Fixes Checklist for File Explorer

### ISSUE THREAD

**Issue by SwapnilChand** [Cloud-Code-AI/AkiraDocs#213]
## Description
This issue outlines a series of UI fixes needed for the file explorer component. The goal is to enhance user experience by addressing various visual and functional inconsistencies. The following items need to be implemented to improve the overall usability and aesthetic of the interface.
- [x] **Combine Editor and Explorer**: #198 
- [x] **Simpler Project Explorer UI**: Remove shadow effects and padding (p-0) from the project explorer component.
- [x] **Add a context menu**: Replace the buttons for adding and deleting files / folders, with a context menu. #200 
- [x] **Remove folder guide borders**: Remove guiding lines seen within an expanded folder, for a clean UI.
- [x] **Hide .json file extensions**: Use the following code snippet to hide ".json" from being displayed in the UI:
  ```javascript
  {node.type === "file" ? node.name.split('.').slice(0, -1).join('.') : node.name}
- [x] **Language Drop down menu**
- [x] **Insertion Point** 
- [x] **Hide _meta files**: Ensure that any _meta files are not visible to the users in the editor interface.
- [x] **Remove folder and file icons**: Eliminate folder and file icons from the UI for a cleaner look. Consider only having an icon for files.
- [x] **Remove back and EditMode**: #220 
- [x] **Add ellipsis for folder names**: Implement functionality to truncate folder names that exceed the width of the explorer, adding ellipsis (e.g., "VeryLongFolderName..." similar to VS Code).
- [x] **Renaming files/folders**: Allow renaming of files/folders #219 / #227
- [x] **Enhance new file opening exp**: #219 
- [x] **Autofocus on input element**: Ensure that the cursor focusses within the block / file-folder name input, seamlessly without needing a user mouse click. #212 / #180
- [ ] **Rendering of empty folders**: Allow folders without any files to get rendered in the UI.

**Comment by SwapnilChand** [comment]
The above changes are being added to a personal fork of this repo https://github.com/SwapnilChand/akiradocs-template/tree/ui-fixes.
